# Generated by Django 4.0 on 2022-07-10 23:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('phones', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=60, unique=True)),
                ('is_locked', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vendor_sku', models.IntegerField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, upload_to='certificates')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('date_purchased', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('add_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_by', to='users.customuser')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.customuser')),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairs', to='users.customuser')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phones.grade')),
                ('location', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='phones.location')),
                ('phonespec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='phones.phonespec')),
            ],
            options={
                'verbose_name': '1. All Phones',
            },
        ),
        migrations.CreateModel(
            name='TestResultUnlocked',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lcd', models.BooleanField(verbose_name='LCD Faulty')),
                ('digitizer', models.BooleanField(verbose_name='Digitizer Faulty')),
                ('rear_camera', models.BooleanField(verbose_name='Rear Camera Faulty')),
                ('front_camera', models.BooleanField(verbose_name='Front Camera Faulty')),
                ('baseband', models.BooleanField(verbose_name='Baseband Issue')),
                ('face_id', models.BooleanField(verbose_name='Face ID Issue')),
                ('wifi_bluetooth', models.BooleanField(verbose_name='Wifi/Bluetooth Issue')),
                ('sound', models.BooleanField(verbose_name='Audio Issue')),
                ('charging_port', models.BooleanField(verbose_name='Charging Port Faulty')),
                ('housing', models.BooleanField(verbose_name='Back Cover Broken')),
                ('total_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('final_worth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Final Worth (Autofilled)')),
                ('profitless', models.BooleanField(verbose_name='No Profit, for Parts Only')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('phone', models.OneToOneField(limit_choices_to={'is_locked': False}, on_delete=django.db.models.deletion.CASCADE, to='techs.phone')),
                ('price_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.unlockedpartscost', verbose_name='Part Price (Autofilled)')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.customuser')),
            ],
            options={
                'verbose_name': '3. Unlocked Phone Test Result',
            },
        ),
        migrations.CreateModel(
            name='TestResultLocked',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=15, max_digits=6)),
                ('screen', models.BooleanField(default=0, verbose_name='Screen OK')),
                ('housing', models.BooleanField(verbose_name='Housing OK')),
                ('back_camera', models.BooleanField(verbose_name='Back Camera OK')),
                ('charging_port', models.BooleanField(verbose_name='Charging Port OK')),
                ('final_worth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Final_worth (Autofilled)')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('phone', models.OneToOneField(limit_choices_to={'is_locked': True}, on_delete=django.db.models.deletion.CASCADE, to='techs.phone')),
                ('price_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.lockedpartsworth', verbose_name='Part Worth (Autofilled)')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.customuser')),
            ],
            options={
                'verbose_name': '2. Locked Phone Test Result',
            },
        ),
        migrations.CreateModel(
            name='PhoneComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='techs.phone')),
            ],
            options={
                'verbose_name': '4. Comments',
            },
        ),
    ]
