# Generated by Django 4.0 on 2022-07-21 08:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phones', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_ready_for_sales', models.BooleanField(default=0, verbose_name='Ready For Sale Phone')),
                ('imei', models.CharField(max_length=60, unique=True)),
                ('is_locked', models.CharField(choices=[('PE', 'Pending'), ('LO', 'Locked'), ('UN', 'Unlock'), ('FA', 'Failed')], default='PE', max_length=2, verbose_name='Lock Status')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vendor_sku', models.CharField(blank=True, max_length=50, null=True)),
                ('certificate', models.FileField(blank=True, upload_to='certificates')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('date_purchased', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('add_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_by', to='users.customuser')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.customuser')),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairs', to='users.customuser')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phones.grade')),
                ('location', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='phones.location')),
                ('phonespec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='phones.phonespec')),
            ],
            options={
                'verbose_name': '1. All Phones',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_tested', models.BooleanField(default=False, verbose_name='Already Tested')),
                ('label_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lcd', models.BooleanField(default=0, verbose_name='LCD Faulty')),
                ('digitizer', models.BooleanField(default=0, verbose_name='Digitizer Faulty')),
                ('rear_camera', models.BooleanField(default=0, verbose_name='Rear Camera Faulty')),
                ('front_camera', models.BooleanField(default=0, verbose_name='Front Camera Faulty')),
                ('baseband', models.BooleanField(default=0, verbose_name='Baseband Issue')),
                ('face_id', models.BooleanField(default=0, verbose_name='Face ID Issue')),
                ('wifi_bluetooth', models.BooleanField(default=0, verbose_name='Wifi/Bluetooth Issue')),
                ('sound', models.BooleanField(default=0, verbose_name='Audio Issue')),
                ('charging_port', models.BooleanField(default=0, verbose_name='Charging Port Faulty')),
                ('housing', models.BooleanField(default=0, verbose_name='Back Cover Broken')),
                ('total_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('has_profit', models.BooleanField(default=False, verbose_name='Worth to Repair')),
                ('locked_labor_cost', models.DecimalField(decimal_places=2, default=15, max_digits=6)),
                ('locked_screen', models.BooleanField(default=0, verbose_name='Screen OK')),
                ('locked_housing', models.BooleanField(default=0, verbose_name='Housing OK')),
                ('locked_back_camera', models.BooleanField(default=0, verbose_name='Back Camera OK')),
                ('locked_charging_port', models.BooleanField(default=0, verbose_name='Charging Port OK')),
                ('final_worth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Final_worth (Autofilled)')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('locked_price_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.lockedpartsworth', verbose_name='Part Worth (Autofilled)')),
                ('phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_form', to='techs.phone')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.customuser')),
                ('unlock_price_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.unlockedpartscost', verbose_name='Part Price (Autofilled)')),
            ],
            options={
                'verbose_name': '2. Phone Test Result',
            },
        ),
        migrations.CreateModel(
            name='PhoneComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='techs.phone')),
            ],
            options={
                'verbose_name': '4. Comments',
            },
        ),
    ]
