# Generated by Django 4.0 on 2022-07-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='has_profit',
            field=models.BooleanField(default=False, verbose_name='Ok to repair'),
        ),
    ]
