# Generated by Django 4.0 on 2022-07-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='is_locked',
            field=models.CharField(choices=[('PE', 'Pending'), ('LO', 'Locked'), ('UN', 'Unlock')], default='PE', max_length=2),
        ),
    ]
