# Generated by Django 4.0 on 2022-07-18 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
        ('techs', '0002_alter_phone_phonespec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phonespec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='phones.phonespec'),
            preserve_default=False,
        ),
    ]
