# Generated by Django 4.0 on 2022-07-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0004_alter_testresult_baseband_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='is_locked',
            field=models.CharField(choices=[('PE', 'Pending'), ('LO', 'Locked'), ('UN', 'Unlock'), ('FA', 'Failed')], default='PE', max_length=2),
        ),
    ]
