# Generated by Django 4.0 on 2022-07-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('Warehouse', 'Warehouse'), ('Repairs', 'Repairs'), ('Customers', 'Customers')], default='Repairs', max_length=10),
        ),
    ]
