# Generated by Django 4.0 on 2022-07-06 12:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=20, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='phones.brand')),
            ],
        ),
        migrations.CreateModel(
            name='UnlockedPartsCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lcd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('digitizer', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rear_camera', models.DecimalField(decimal_places=2, max_digits=6)),
                ('front_camera', models.DecimalField(decimal_places=2, max_digits=6)),
                ('baseband', models.DecimalField(decimal_places=2, max_digits=6)),
                ('face_id', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wifi_bluetooth', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sound', models.DecimalField(decimal_places=2, max_digits=6)),
                ('charging_port', models.DecimalField(decimal_places=2, max_digits=6)),
                ('housing', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parts_cost', to='phones.model')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(choices=[('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB')], max_length=5)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='phones.model')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_prices', to='phones.model')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_prices', to='phones.storage')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=30, null=True)),
                ('listing_id', models.IntegerField(blank=True, null=True)),
                ('sku', models.IntegerField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phonespec', to='phones.color')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phonespec', to='phones.model')),
                ('purchase_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phonespec', to='phones.purchaseprice')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phonespec', to='phones.storage')),
            ],
        ),
        migrations.CreateModel(
            name='LockedPartsWorth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screen', models.DecimalField(decimal_places=2, max_digits=6)),
                ('housing', models.DecimalField(decimal_places=2, max_digits=6)),
                ('back_camera', models.DecimalField(decimal_places=2, max_digits=6)),
                ('charging_port', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parts_worth', to='phones.model')),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='phones.model'),
        ),
        migrations.AddConstraint(
            model_name='storage',
            constraint=models.UniqueConstraint(fields=('model', 'storage'), name='unique_storage_for_model'),
        ),
        migrations.AddConstraint(
            model_name='purchaseprice',
            constraint=models.UniqueConstraint(fields=('model', 'storage'), name='unique_price_give_model_and_storage'),
        ),
        migrations.AddConstraint(
            model_name='phonespec',
            constraint=models.UniqueConstraint(fields=('model', 'storage', 'color', 'purchase_price'), name='unique_phonespec_detail'),
        ),
        migrations.AddConstraint(
            model_name='model',
            constraint=models.UniqueConstraint(fields=('model', 'brand'), name='unique_model_brand'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('model', 'color'), name='unique_color_for_model'),
        ),
    ]
