# Generated by Django 4.0 on 2022-07-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonespec',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
